export const projects = [
  {
    title: 'ISA',
    description: "A sustainable and automatic greenhouse that uses AI and server communication",
      image: '/images/ISA.png',
      tags: ['C++', 'TensorFlow', 'React Native', 'NodeJs'],
    source: 'https://github.com/papalino456/ISA',
    visit: 'http://sb-isa.herokuapp.com',
    id: 0,
  },
  {
    title: 'Python RayTracer',
    description:"A simple image raytracer made with python that features specular and difuse reflections",
    image: '/images/test.png',
    tags: ['Python'],
    source: 'https://github.com/papalino456/RayTracer_Python',
    visit: 'https://github.com/papalino456/RayTracer_Python',
    id: 1,
  },
  {
    title: 'Covid Tracker',
    description: "A web app that keeps daily track of covid infections, deaths and recoveries making use of an API",
      image: '/images/Covid.png',
      tags: ['React', "NodeJS","MaterialUI", "Axios"],
    source: 'https://github.com/papalino456/CovidTracker-mathdroAPI',
    visit: 'https://papalino456.github.io/CovidTracker-mathdroAPI/',
    id: 2,
  },
  {
    title: 'Conways Game of Life',
    description: "My own implementation of Conway's game of life using Python and PyGame made from scratch",
    image: '/images/Conways.png',
    tags: ['Python', 'Pygame'],
    source: 'https://github.com/papalino456/ConwaysGameOfLife',
    visit: 'https://github.com/papalino456/ConwaysGameOfLife',
    id: 3,
  },
  {
    title: 'Primordial Particle System',
    description: "A cellular automata not limited to a grid, capable of forming cells, spores and other intricate forms",
    image: '/images/PPS.PNG',
    tags: ['Python', 'Pygame'],
    source: 'https://github.com/papalino456/PrimordialParticleSystem',
    visit: 'https://github.com/papalino456/PrimordialParticleSystem',
    id: 4,
  },
  {
    title: 'Face Tracker',
    description: "An openCV recognition software communicated to an arduino 2 axis servo configuration to keep face centered on camera",
    image: '/images/tracker.PNG',
    tags: ['C++', "Python", 'OpenCV', "Arduino"],
    source: 'https://github.com/papalino456/Face_recognition_python-and_Arduino_tracker',
    visit: 'https://github.com/papalino456/Face_recognition_python-and_Arduino_tracker',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2010, text: 'Started my journey at 7 years old', },
  { year: 2015, text: 'Went to my firt national robotics Tournament', },
  { year: 2017, text: 'Won the International Robotics Championship Robocup', },
  { year: 2019, text: 'Started teaching my own programming courses', },
  { year: 2021, text: 'Currently in search of new challenges', },
];